// USER_ROLE
export const START_FETCHING_USER_ROLE = 'START_FETCHING_USER_ROLE';
export const STOP_FETCHING_USER_ROLE = 'STOP_FETCHING_USER_ROLE';
export const FAIL_FETCHING_USER_ROLE = 'FAIL_FETCHING_USER_ROLE';
export const FINISH_FETCHING_USER_ROLE = 'FINISH_FETCHING_USER_ROLE';

export const START_UPDATING_USER_ROLE = 'START_UPDATING_USER_ROLE';
export const STOP_UPDATING_USER_ROLE = 'STOP_UPDATING_USER_ROLE';
export const FAIL_UPDATING_USER_ROLE = 'FAIL_UPDATING_USER_ROLE';
export const FINISH_UPDATING_USER_ROLE = 'FINISH_UPDATING_USER_ROLE';

export const START_CREATING_USER_ROLE = 'START_CREATING_USER_ROLE';
export const STOP_CREATING_USER_ROLE = 'STOP_CREATING_USER_ROLE';
export const FAIL_CREATING_USER_ROLE = 'FAIL_CREATING_USER_ROLE';
export const FINISH_CREATING_USER_ROLE = 'FINISH_CREATING_USER_ROLE';

export const START_DELETING_USER_ROLE = 'START_DELETING_USER_ROLE';
export const STOP_DELETING_USER_ROLE = 'STOP_DELETING_USER_ROLE';
export const FAIL_DELETING_USER_ROLE = 'FAIL_DELETING_USER_ROLE';
export const FINISH_DELETING_USER_ROLE = 'FINISH_DELETING_USER_ROLE';

// Pagination is not included in this challenge
// USER_ROLE_COLLECTION
export const START_FETCHING_USER_ROLE_COLLECTION = 'START_FETCHING_USER_ROLE_COLLECTION';
export const STOP_FETCHING_USER_ROLE_COLLECTION = 'STOP_FETCHING_USER_ROLE_COLLECTION';
export const FAIL_FETCHING_USER_ROLE_COLLECTION = 'FAIL_FETCHING_USER_ROLE_COLLECTION';
export const FINISH_FETCHING_USER_ROLE_COLLECTION = 'FINISH_FETCHING_USER_ROLE_COLLECTION';

// filtering
export const FILTER_USER_ROLE = 'FILTER_USER_ROLE';

// Batch Updating is not included in this challenge but is useful when dealing
// with real world application
export const START_UPDATING_USER_ROLE_COLLECTION = 'START_UPDATING_USER_ROLE_COLLECTION';
export const STOP_UPDATING_USER_ROLE_COLLECTION = 'STOP_UPDATING_USER_ROLE_COLLECTION';
export const FAIL_UPDATING_USER_ROLE_COLLECTION = 'FAIL_UPDATING_USER_ROLE_COLLECTION';
export const FINISH_UPDATING_USER_ROLE_COLLECTION = 'FINISH_UPDATING_USER_ROLE_COLLECTION';
